version: 2

defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/node:10

jobs:
  install_lint:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-10-cache-{{ checksum "./yarn.lock" }}
      - run: yarn install
      - run: yarn audit
      - run: yarn lint
      - save_cache:
          paths:
            - ~/.yarn-cache
            - ./node_modules
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    <<: *defaults
    steps:
      - attach_workspace:
          as: ~/repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npx semantic-release

workflows:
  version: 2
  install_lint_deploy:
    jobs:
      - install_lint
      - deploy:
          requires:
            - install_lint
          filters:
            branches:
              only:
                - master
